[package]
name = "inner"
version = "0.1.0"
authors = ["CrLF0710"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linkme = "0.2.2"
